/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:3edde058-8abb-4fd0-8efa-5d1be07dcaf3",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_ZUVpP8K8h",
    "aws_user_pools_web_client_id": "698qtb2oi5do4199ue1fqc5uqh",
    "oauth": {}
};


export default awsmobile;
