/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:3edde058-8abb-4fd0-8efa-5d1be07dcaf3",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_ZUVpP8K8h",
    "aws_user_pools_web_client_id": "698qtb2oi5do4199ue1fqc5uqh",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pxdpasrfxfbzfh7gvnyb74fwdu.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jpxtjokkgfeyriqtj26v7kp4ie"
};


export default awsmobile;
